setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pystore.urls')),
    path('', include('user.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path
from user.views import login, register, logout

urlpatterns = [
    path('login', login, name='login'),
    path('register', register, name='register'),
    path('logout', logout, name='logout'),
]

pystore/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User

class Banner(models.Model):
    img = models.ImageField(upload_to="banner_img/")
    alt_text = models.CharField(max_length=250)

    def __str__(self):
        return self.alt_text
    
class Category(models.Model):
    title = models.CharField(max_length=150, null=False, blank=True, default="")
    image = models.ImageField(upload_to='cat_photos/', blank=True)

    def __str__(self):
        return self.title

class Brand(models.Model):
    title = models.CharField(max_length=100, null=False, blank=True, default="")
    image = models.ImageField(upload_to='brand_photos/', blank=True)

    def __str__(self):
        return self.title

class Color(models.Model):
    title = models.CharField(max_length=50)
    color_code = models.CharField(max_length=50)

    def color_tag_path(self):
        return mark_safe(self.color_code)
        
    def __str__(self):
        return self.title

class Size(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title
    
class Product(models.Model):
    title = models.CharField(max_length=150)
    image = models.ImageField(upload_to='product_photos/', blank=True)
    slug = models.CharField(max_length=250)
    detail = models.TextField()
    specification = models.TextField()
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    is_featured_product = models.BooleanField(default=False)

    def __str__(self):
        return self.title

class ProductAttribute(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.product.title
    
class Bag(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    items = models.ManyToManyField('Product', through='ItemBag')

    def __str__(self):
        return f'Bag for {self.user}'

class ItemBag(models.Model):
    bag = models.ForeignKey(Bag, on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1) 

    def __str__(self):
        return f'{self.quantity} of {self.product} in {self.bag}'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <header>
        <h1>Pystore</h1>
        <nav>
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'index' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'categories' %}">Categories</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'brand' %}">Brand</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Bag</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fa fa-user"></i> My account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        
                        <a class="dropdown-item" href="">Login</a>
                        <a class="dropdown-item" href="">Register</a>
                        <a class="dropdown-item" href="">Logout</a>
                    </div>
                   </li>
            </ul>
        </nav></br>
        <nav class="navbar navbar-light bg-light">
            <form class="form-inline d-flex">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-sm btn-outline-primary" type="submit">Search</button>
            </form>
          </nav>
    </header>
</head>
<body>
    {% block content %} {% endblock %}
    {% include 'partials/_footer.html' %}
</body>

</html>

templates/categories.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="banner">
    <img src = "{% static 'media/banner/banner.jpg' %}" alt="banner">
</section>
    <section class="produtos">
        <h3>Categories</h3>
            {% if data %}
                    <div class="produtos-grid">
                        {% for cat in data %}
                        <div class="produto">
                            <a href="{% url 'category_product_list.' cat.id %}"><img src="/media/{{ cat.image }}" alt="{{ cat.title }}"></a>
                            <h4><a href="{% url 'category_product_list' cat.id %}">{{ cat.title }}</a></h4>
                        </div>
                {% endfor %}                    
                    </div>
            {% endif %}
    </section> 
{% endblock %}

templates/category_product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="banner">
    <img src = "{% static 'media/banner/banner.jpg' %}" alt="banner">
</section>
<section class="produtos">
	<h3 class="mb-4 border-bottom pb-1">Products</h3>
			<div class="produtos-grid">
				{% for product in data %}
				<div class="produto">
					<a href="/category_product_list/{{ product.id }}{{ product.productattribute_set.first.price }}"><img src="/media/{{ product.image }}" alt="{{ product.title }}"></a>
					<h5><a href="/product/{{ product.slug }}/{{ product.id }}/{{ product.productattribute_set.first.price }}">{{ product.title }}</a></h5>
              	{% for attribute in product.productattribute_set.all %}
				  <h6>€{{ attribute.price }} <span class=""></span></h6>
              	{% endfor %}
				</div>
				{% endfor %}
			</div>
</section>
{% endblock %}

templates/filters.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<script type="text/javascript" src="{% static 'product-filter.js' %}"></script>
			<h3 class="mb-4 border-bottom pb-1">Filters</h3>
			
			<div class="card mb-4">
				<h6 class="card-header">Price</h6>
				<div class="list-group list-group-flush">
					<li class="list-group-item">
						<input type="range" value="{{minMaxPrice.price__min}}" max={{minMaxPrice.price__max}} min={{minMaxPrice.price__min}} id="rangeInput" oninput="maxPrice.value=this.value" />
						<p>{{minMaxPrice.price__min}}-{{minMaxPrice.price__max}}</p>
					</li>
					<li class="list-group-item">
						Maximum: <input type="number" value="{{minMaxPrice.price__min}}" max={{minMaxPrice.price__max}} min={{minMaxPrice.price__min}} class="form-control" id="maxPrice" onkeyup="rangeInput.value=this.value" id="maxPrice" />
						<button id="priceFilterBtn" class="btn btn-info btn-sm mt-1">Filters</button>
					</li>
				</div>
			</div>
			
			<div class="card mb-4">
				<h6 class="card-header">Colors</h6>
				<div class="list-group list-group-flush">
					{% for color in colors %}
					<li class="list-group-item">
						<input class="filter-checkbox" data-filter="color" value="{{color.color__id}}" type="checkbox" />&nbsp;
						<button class="btn" style="background-color: {{color.color__color_code}}; margin-top: -5px;"></button>
					</li>
					{% endfor %}
				</div>
			</div>
		
			<div class="card mb-4">
				<h6 class="card-header">Categories</h6>
				<div class="list-group list-group-flush">
					{% for cat in catagory %}
					<li class="list-group-item">
						<input class="filter-checkbox" data-filter="category" value="{{cat.category__id}}" type="checkbox" />&nbsp;
						{{cat.category__title}}
					</li>
					{% endfor %}
				</div>
			</div>
		
			<div class="card mb-4">
				<h6 class="card-header">Brands</h6>
				<div class="list-group list-group-flush">
					{% for brand in brands %}
					<li class="list-group-item">
						<input class="filter-checkbox" data-filter="brand" value="{{brand.brand__id}}" type="checkbox" />&nbsp;
						{{brand.brand__title}}
					</li>
					{% endfor %}
				</div>
			</div>
			
			<div class="card mb-4">
				<h6 class="card-header">Sizes</h6>
				<div class="list-group list-group-flush">
					{% for size in sizes %}
					<li class="list-group-item">
						<input class="filter-checkbox" data-filter="size" value="{{size.size__id}}" type="checkbox" />&nbsp;
						{{size.size__title}}
					</li>
					{% endfor %}
				</div>
			</div>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main>
        <section class="banner">
            <img src = "{% static 'media/banner/banner.jpg' %}" alt="banner">
        </section>
        <section class="produtos">
            <h2>Featured Products</h2>
            <div class="produtos-grid">
                {% for product in data %}
            <div class="produto">
                <img src="{{ product.image.url }}" alt="{{ product.title }}">
                <h3>{{ product.title }}</h3>
                <p>{{ product.description }}</p>
                {% for attribute in product.productattribute_set.all %}
                    <h6><span class="preco">€{{ attribute.price }} <span class=""></span></h6>
                {% endfor %}
                <a href="#" class="btn">Buy</a>
            </div>
        {% endfor %}
            </div>
        </section>
        <p class="my-4 text-center"><a href="{% url 'product' %}" class="btn btn-dark btn-sm">All Products <i class="fa fa-long-arrow-alt-right"></i></a></p>
    </main>
{% endblock %}

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="banner">
	<img src = "{% static 'media/banner/banner.jpg' %}" alt="banner">
</section>
<main class="container my-4">
	<div class="row">
		<div class="col-md-3">
			{% include 'filters.html' %}
		</div>
		<div class="col-md-9">
			
			<h3 class="mb-4 border-bottom pb-1">Products</h3>
			<div class="row" id="filteredProducts">
				<p class="ajaxLoader">Loading...</p>
				{% for product in data %}
				<div class="col-lg-4 col-md-6 mb-4 product-box">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{ product.id }}/{{ product.productattribute_set.first.price }}"><img src="/media/{{ product.image }}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h5 class="card-text"><a href="/product/{{ product.slug }}/{{product.id}}/{{ product.productattribute_set.first.price }}">{{ product.title }}</a></h5>
              {% for attribute in product.productattribute_set.all %}
					      <h6>€{{ attribute.price }} <span class=""></span></h6>
              {% endfor %}
					  </div>
					  	<div class="card-footer">
				         
							  	<button class="btn btn-sm btn-primary add-to-cart" data-index=""><i class="fa fa-shopping-cart"></i></button>
							  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
							  	<span class="float-right">
							  		4.5/5
							  		<i class="fa fa-star text-warning"></i>
							  	</span>
					  	</div>
					</div>
				</div>
				{% endfor %}
			</div>
			<p class="my-4 text-center"><button id="loadMore" data-total="" data-limit="3" class="btn btn-dark btn-sm">Load + <i class="fa fa-sync load-more-icon"></i></button></p>
		</div>
	</div>
  
{% endblock %}